import { Job } from './models/jobs.models';

export const jobMock: Job[] = [
  {
    id: 1,
    company: 'Tech Innovations Inc.',
    expires: '2023-12-01',
    position: 'Software Engineer',
    startingSalary: 80000,
    workType: 'remote',
    location: 'San Francisco, CA',
    country: 'USA',
    qualifications: "Bachelor's degree in Computer Science or related field.",
    description:
      'We are looking for a skilled Software Engineer to join our team and contribute to exciting projects.',
    isApplied: false,
  },
  {
    id: 2,
    company: 'Creative Solutions Ltd.',
    expires: '2023-11-15',
    position: 'Product Designer',
    startingSalary: 70000,
    workType: 'hybrid',
    location: 'New York, NY',
    country: 'USA',
    qualifications: 'Proven experience in product design and user experience.',
    description:
      'Join our creative team to design impactful products that enhance user experience.',
    isApplied: true,
  },
  {
    id: 3,
    company: 'Global Finance Corp.',
    expires: '2023-10-30',
    position: 'Financial Analyst',
    startingSalary: 60000,
    workType: 'onsite',
    location: 'Chicago, IL',
    country: 'USA',
    qualifications:
      'Strong analytical skills and a degree in Finance or Economics.',
    description:
      'We are seeking a detail-oriented Financial Analyst to provide insights and support for our financial planning.',
    isApplied: false,
  },
  {
    id: 4,
    company: 'Green Tech Solutions',
    expires: '2023-11-20',
    position: 'Environmental Consultant',
    startingSalary: 75000,
    workType: 'remote',
    location: 'Austin, TX',
    country: 'USA',
    qualifications: 'Experience in environmental science or sustainability.',
    description:
      'Help businesses reduce their environmental impact with our expert consultancy.',
    isApplied: false,
  },
  {
    id: 5,
    company: 'HealthPlus',
    expires: '2023-11-25',
    position: 'Project Manager',
    startingSalary: 90000,
    workType: 'hybrid',
    location: 'Boston, MA',
    country: 'USA',
    qualifications: '3+ years of project management experience in healthcare.',
    description:
      'Lead projects to improve healthcare delivery and patient outcomes.',
    isApplied: false,
  },
  {
    id: 6,
    company: 'Innovative Marketing Agency',
    expires: '2023-12-05',
    position: 'Digital Marketing Specialist',
    startingSalary: 65000,
    workType: 'remote',
    location: 'Los Angeles, CA',
    country: 'USA',
    qualifications: 'Experience with SEO, PPC, and social media marketing.',
    description:
      'Join our team to develop and execute digital marketing campaigns.',
    isApplied: true,
  },
  {
    id: 7,
    company: 'Retail Giants',
    expires: '2023-11-30',
    position: 'Sales Associate',
    startingSalary: 40000,
    workType: 'onsite',
    location: 'Miami, FL',
    country: 'USA',
    qualifications:
      'Excellent customer service skills and a passion for retail.',
    description: 'Assist customers and drive sales in our flagship store.',
    isApplied: false,
  },
  {
    id: 8,
    company: 'Cybersecurity Solutions',
    expires: '2023-12-10',
    position: 'Cybersecurity Analyst',
    startingSalary: 85000,
    workType: 'remote',
    location: 'Seattle, WA',
    country: 'USA',
    qualifications: 'Knowledge of network security and risk assessment.',
    description: "Protect our clients' data and systems from cyber threats.",
    isApplied: false,
  },
  {
    id: 9,
    company: 'Global Logistics Co.',
    expires: '2023-10-28',
    position: 'Logistics Coordinator',
    startingSalary: 50000,
    workType: 'onsite',
    location: 'Dallas, TX',
    country: 'USA',
    qualifications: 'Strong organizational skills and experience in logistics.',
    description: 'Coordinate shipments and ensure timely delivery of goods.',
    isApplied: false,
  },
  {
    id: 10,

    company: 'EduTech',
    expires: '2023-12-15',
    position: 'Content Writer',
    startingSalary: 55000,
    workType: 'remote',
    location: 'Denver, CO',
    country: 'USA',
    qualifications:
      'Strong writing skills and experience in educational content.',
    description: 'Create engaging content for our online learning platform.',
    isApplied: true,
  },
  {
    id: 11,
    company: 'Smart Home Solutions',
    expires: '2023-11-18',
    position: 'Electrical Engineer',
    startingSalary: 78000,
    workType: 'onsite',
    location: 'Phoenix, AZ',
    country: 'USA',
    qualifications: "Bachelor's degree in Electrical Engineering.",
    description: 'Design and develop innovative smart home products.',
    isApplied: false,
  },
  {
    id: 12,
    company: 'Travel Adventures Inc.',
    expires: '2023-11-22',
    position: 'Travel Agent',
    startingSalary: 45000,
    workType: 'hybrid',
    location: 'Orlando, FL',
    country: 'USA',
    qualifications: 'Passion for travel and experience in customer service.',
    description: 'Help clients plan their dream vacations.',
    isApplied: false,
  },
  {
    id: 13,
    company: 'Foodies United',
    expires: '2023-12-12',
    position: 'Chef',
    startingSalary: 60000,
    workType: 'onsite',
    location: 'New Orleans, LA',
    country: 'USA',
    qualifications: 'Culinary degree and experience in a fast-paced kitchen.',
    description: 'Create delicious dishes for our restaurant.',
    isApplied: true,
  },
  {
    id: 14,

    company: 'Innovate AI',
    expires: '2023-12-20',
    position: 'Data Scientist',
    startingSalary: 95000,
    workType: 'remote',
    location: 'Atlanta, GA',
    country: 'USA',
    qualifications: 'Experience with machine learning and data analysis.',
    description: 'Analyze data to develop AI-driven insights.',
    isApplied: false,
  },
  {
    id: 15,
    company: 'Brew Masters Co.',
    expires: '2023-11-05',
    position: 'Brewmaster',
    startingSalary: 70000,
    workType: 'onsite',
    location: 'Portland, OR',
    country: 'USA',
    qualifications: 'Experience in brewing and a passion for craft beer.',
    description: 'Oversee the brewing process and ensure quality.',
    isApplied: false,
  },
  {
    id: 16,
    company: 'Smart Health Solutions',
    expires: '2023-11-28',
    position: 'Nurse Practitioner',
    startingSalary: 100000,
    workType: 'onsite',
    location: 'San Diego, CA',
    country: 'USA',
    qualifications: 'Valid NP license and experience in a clinical setting.',
    description: 'Provide high-quality patient care in our clinic.',
    isApplied: true,
  },
  {
    id: 17,
    company: 'NextGen Robotics',
    expires: '2023-12-03',
    position: 'Robotics Engineer',
    startingSalary: 85000,
    workType: 'remote',
    location: 'Boston, MA',
    country: 'USA',
    qualifications: 'Experience in robotic systems and programming.',
    description: 'Design and develop advanced robotic systems.',
    isApplied: false,
  },
  {
    id: 18,
    company: 'Fashion Forward',
    expires: '2023-11-10',
    position: 'Fashion Designer',
    startingSalary: 65000,
    workType: 'hybrid',
    location: 'Los Angeles, CA',
    country: 'USA',
    qualifications: 'Degree in Fashion Design and a strong portfolio.',
    description: 'Create innovative fashion designs for our new collection.',
    isApplied: false,
  },
  {
    id: 19,
    company: 'City Transport Services',
    expires: '2023-11-27',
    position: 'Transportation Planner',
    startingSalary: 70000,
    workType: 'onsite',
    location: 'Seattle, WA',
    country: 'USA',
    qualifications: 'Experience in urban planning and transportation systems.',
    description: 'Develop plans to enhance the efficiency of public transport.',
    isApplied: true,
  },
  {
    id: 20,
    company: 'Elder Care Services',
    expires: '2023-12-08',
    position: 'Home Health Aide',
    startingSalary: 35000,
    workType: 'onsite',
    location: 'Miami, FL',
    country: 'USA',
    qualifications: 'Compassionate and experienced in elder care.',
    description:
      'Provide care and assistance to elderly clients in their homes.',
    isApplied: false,
  },
];
